language: android

os: linux
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev # https://github.com/nodegit/nodegit/issues/853
      - gcc-4.8
      - g++-4.8

android:
  components:
    - tools
    - tools # Duplicated as per https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - build-tools-26.0.2
    - android-26
    - platform-tools
    - extra-android-m2repository

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/"${BAZEL_VERSION}"/bazel_"${BAZEL_VERSION}"-linux-x86_64.deb
  - sudo dpkg -i bazel_"${BAZEL_VERSION}"-linux-x86_64.deb
  - sudo rm -f /etc/mavenrc
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar -zxf apache-maven-3.1.1-bin.tar.gz
  - export PATH="$PWD/apache-maven-3.1.1/bin:$PATH"
  - mkdir travis_bin
  - ln -s $(which gcc-4.8) travis_bin/gcc
  - ln -s $(which g++-4.8) travis_bin/g++
  - export PATH="${PWD}/travis_bin:${PATH}"

script: ./build_test.sh

env:
  global:
    - BAZEL_VERSION="0.29.1"

branches:
  only:
    - master
    - /^release.*$/
